In [ ]:
from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_excel("ex.xlsx")
df

Saving ex.xlsx to ex.xlsx

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,"Kumar Sanu, Mika Singh, Neha Kakkar",BollywoodDance,Simmba,8.8/10
1,Coca Cola,"Neha Kakkar, Tony Kakkar",BollywoodDanceRomantic,Luka Chuppi,9.0/10
2,Apna Time Aayega,Ranveer Singh,BollywoodDance,Gully Boy,9.7/10
3,Mungda,"Jyotica Tangri, Shaan, Subhro Ganguly",BollywoodDance,Total Dhamaal,9.1/10
4,Tere Bin,"Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi",BollywoodRomantic,Simmba,9.2/10
...,...,...,...,...,...
2415,Jana Tumhare Pyar Mein,Mukesh,BollywoodDance,Sasural,6.2/10
2416,Tum Jaise Bigde Babu Se,Lata Mangeshkar,BollywoodDance,Jab Pyar Kisi Se Hota Hai,7.2/10
2417,O Yaad Nahi Bhool Gaya,"Lata Mangeshkar, Suresh Wadkar",BollywoodDance,Lamhe,7.5/10
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,Jagjit Kaur,BollywoodDance,Shola Aur Shabnam,6.5/10
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,Asha Bhosle,BollywoodDance,Shola Aur Shabnam,6.6/10

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df.isnull().sum()

Song-Name          0
Singer/Artists    10
Genre              0
Album/Movie        3
User-Rating        0
dtype: int64

In [ ]:
df.dropna(inplace = True)

In [ ]:
df.isnull().sum()

Song-Name         0
Singer/Artists    0
Genre             0
Album/Movie       0
User-Rating       0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(16)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(2391, 5)

In [ ]:
df.head()

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,"Kumar Sanu, Mika Singh, Neha Kakkar",BollywoodDance,Simmba,8.8/10
1,Coca Cola,"Neha Kakkar, Tony Kakkar",BollywoodDanceRomantic,Luka Chuppi,9.0/10
2,Apna Time Aayega,Ranveer Singh,BollywoodDance,Gully Boy,9.7/10
3,Mungda,"Jyotica Tangri, Shaan, Subhro Ganguly",BollywoodDance,Total Dhamaal,9.1/10
4,Tere Bin,"Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi",BollywoodRomantic,Simmba,9.2/10

In [ ]:
df['User-Rating']

0       8.8/10
1       9.0/10
2       9.7/10
3       9.1/10
4       9.2/10
         ...
2415    6.2/10
2416    7.2/10
2417    7.5/10
2418    6.5/10
2419    6.6/10
Name: User-Rating, Length: 2391, dtype: object

In [ ]:
l = []
for i in df['User-Rating']:
  l.append(i[:3])
l

['8.8',
 '9.0',
 '9.7',
 '9.1',
 '9.2',
 '9.1',
 '9.2',
 '9.5',
 '9.2',
 '9.6',
 '8.8',
 '8.4',
 '9.1',
 '9.2',
 '9.0',
 '9.7',
 '9.1',
 '9.0',
 '9.0',
 '9.1',
 '9.2',
 '9.2',
 '9.5',
 '8.6',
 '9.1',
 '9.0',
 '9.0',
 '9.2',
 '9.5',
 '9.4',
 '8.7',
 '9.3',
 '9.3',
 '9.5',
 '9.1',
 '9.0',
 '9.0',
 '9.1',
 '8.4',
 '8.4',
 '8.8',
 '9.2',
 '9.2',
 '9.6',
 '9.6',
 '9.0',
 '9.1',
 '8.5',
 '9.5',
 '8.5',
 '9.7',
 '8.9',
 '9.6',
 '8.5',
 '9.1',
 '8.7',
 '8.6',
 '9.3',
 '9.7',
 '8.9',
 '9.0',
 '9.0',
 '9.3',
 '9.3',
 '9.1',
 '9.0',
 '9.7',
 '9.2',
 '9.1',
 '9.0',
 '8.9',
 '9.5',
 '9.5',
 '9.7',
 '9.0',
 '8.1',
 '8.1',
 '9.5',
 '9.1',
 '8.6',
 '9.4',
 '9.0',
 '9.0',
 '9.6',
 '9.3',
 '9.0',
 '9.2',
 '9.3',
 '9.1',
 '8.6',
 '9.5',
 '9.5',
 '9.0',
 '9.4',
 '9.2',
 '9.6',
 '9.3',
 '7.7',
 '9.2',
 '9.3',
 '7.7',
 '9.0',
 '9.5',
 '9.4',
 '9.0',
 '9.2',
 '9.0',
 '9.4',
 '9.4',
 '9.1',
 '9.3',
 '9.2',
 '9.1',
 '9.0',
 '9.8',
 '8.9',
 '6.8',
 '8.9',
 '8.2',
 '8.7',
 '8.2',
 '9.4',
 '9.0',
 '8.9',
 '9.9',
 '8.7',
 '8.9',
 '9.6',
 '9.5',
 '8.7',
 '8.4',
 '9.5',
 '9.3',
 '8.3',
 '9.2',
 '9.3',
 '8.9',
 '8.7',
 '9.1',
 '9.6',
 '9.4',
 '9.6',
 '8.6',
 '9.1',
 '9.2',
 '9.6',
 '9.6',
 '8.8',
 '8.7',
 '9.4',
 '9.0',
 '8.1',
 '9.6',
 '9.3',
 '9.4',
 '9.2',
 '9.5',
 '9.6',
 '9.9',
 '9.4',
 '9.7',
 '9.4',
 '9.4',
 '9.5',
 '9.3',
 '8.1',
 '8.5',
 '9.4',
 '8.6',
 '9.4',
 '9.3',
 '9.1',
 '9.2',
 '9.0',
 '7.2',
 '9.7',
 '8.5',
 '7.7',
 '9.3',
 '9.3',
 '9.7',
 '9.0',
 '9.2',
 '9.2',
 '8.8',
 '9.1',
 '9.3',
 '9.2',
 '9.0',
 '9.2',
 '8.5',
 '9.6',
 '9.3',
 '9.7',
 '8.5',
 '8.9',
 '9.6',
 '8.7',
 '8.4',
 '9.2',
 '9.2',
 '9.1',
 '9.1',
 '8.7',
 '8.9',
 '9.4',
 '8.4',
 '9.0',
 '9.1',
 '9.4',
 '9.6',
 '9.3',
 '9.5',
 '9.5',
 '9.2',
 '7.6',
 '8.9',
 '9.6',
 '9.4',
 '9.4',
 '8.6',
 '9.6',
 '8.9',
 '8.6',
 '9.2',
 '8.7',
 '8.9',
 '8.7',
 '9.6',
 '9.2',
 '9.2',
 '9.2',
 '9.4',
 '9.0',
 '9.4',
 '9.7',
 '8.8',
 '9.6',
 '9.4',
 '8.9',
 '9.4',
 '9.0',
 '9.5',
 '9.5',
 '9.3',
 '9.7',
 '9.0',
 '8.2',
 '9.4',
 '9.1',
 '8.8',
 '9.1',
 '9.2',
 '9.2',
 '9.4',
 '9.0',
 '9.7',
 '9.4',
 '9.1',
 '8.8',
 '9.1',
 '9.1',
 '8.7',
 '9.7',
 '9.4',
 '9.5',
 '8.8',
 '8.9',
 '9.3',
 '8.5',
 '9.3',
 '9.2',
 '9.5',
 '8.9',
 '9.1',
 '9.3',
 '9.4',
 '9.3',
 '9.6',
 '8.8',
 '9.6',
 '9.1',
 '8.8',
 '8.8',
 '9.4',
 '9.4',
 '9.4',
 '8.1',
 '9.0',
 '8.5',
 '7.5',
 '9.3',
 '9.5',
 '7.9',
 '9.0',
 '9.6',
 '9.4',
 '9.5',
 '9.0',
 '9.5',
 '9.5',
 '8.8',
 '9.4',
 '7.3',
 '9.4',
 '9.1',
 '9.6',
 '9.7',
 '8.8',
 '9.1',
 '9.1',
 '9.1',
 '9.0',
 '9.3',
 '8.7',
 '8.2',
 '9.3',
 '9.3',
 '8.4',
 '9.0',
 '9.3',
 '8.9',
 '9.0',
 '9.4',
 '9.1',
 '9.4',
 '9.3',
 '9.6',
 '9.1',
 '9.0',
 '8.9',
 '8.5',
 '9.2',
 '8.2',
 '9.2',
 '9.4',
 '9.3',
 '9.4',
 '9.3',
 '9.3',
 '9.1',
 '9.3',
 '9.2',
 '9.2',
 '9.6',
 '9.4',
 '9.3',
 '9.1',
 '9.3',
 '9.6',
 '9.1',
 '8.8',
 '8.8',
 '9.1',
 '9.3',
 '9.5',
 '9.3',
 '8.8',
 '8.8',
 '9.2',
 '8.7',
 '9.4',
 '9.3',
 '9.1',
 '9.7',
 '8.6',
 '9.1',
 '8.9',
 '9.0',
 '9.2',
 '9.1',
 '9.1',
 '9.1',
 '9.1',
 '9.1',
 '9.1',
 '8.8',
 '8.8',
 '9.4',
 '7.7',
 '8.4',
 '7.4',
 '9.3',
 '9.1',
 '8.7',
 '8.9',
 '9.3',
 '9.4',
 '9.6',
 '9.4',
 '8.7',
 '9.0',
 '9.1',
 '9.1',
 '9.1',
 '9.4',
 '9.4',
 '9.5',
 '9.2',
 '9.3',
 '8.9',
 '8.4',
 '9.0',
 '8.5',
 '8.7',
 '9.2',
 '8.7',
 '9.0',
 '9.4',
 '9.2',
 '9.5',
 '8.7',
 '9.2',
 '8.4',
 '8.9',
 '8.2',
 '8.9',
 '8.6',
 '9.6',
 '9.7',
 '9.4',
 '8.3',
 '9.5',
 '9.3',
 '9.2',
 '8.8',
 '7.9',
 '9.3',
 '8.9',
 '9.4',
 '9.4',
 '8.2',
 '9.2',
 '9.0',
 '9.3',
 '8.9',
 '9.6',
 '9.2',
 '7.9',
 '8.6',
 '9.2',
 '9.2',
 '8.5',
 '9.3',
 '9.6',
 '9.6',
 '9.4',
 '9.1',
 '9.2',
 '8.8',
 '9.1',
 '8.2',
 '9.4',
 '8.6',
 '9.2',
 '9.5',
 '8.4',
 '9.3',
 '7.9',
 '9.2',
 '9.1',
 '9.2',
 '9.1',
 '9.5',
 '9.4',
 '8.8',
 '8.3',
 '8.4',
 '9.0',
 '9.7',
 '8.7',
 '9.5',
 '9.3',
 '9.3',
 '9.2',
 '8.5',
 '9.3',
 '9.3',
 '9.2',
 '9.2',
 '9.2',
 '7.8',
 '8.8',
 '9.4',
 '8.7',
 '9.0',
 '9.4',
 '8.7',
 '8.4',
 '8.7',
 '9.5',
 '9.7',
 '9.3',
 '9.0',
 '8.0',
 '9.2',
 '8.6',
 '9.6',
 '9.1',
 '9.3',
 '7.9',
 '8.7',
 '9.3',
 '9.0',
 '8.8',
 '9.0',
 '9.3',
 '9.3',
 '9.3',
 '9.2',
 '9.2',
 '9.0',
 '8.4',
 '8.9',
 '9.0',
 '9.1',
 '8.1',
 '8.9',
 '9.4',
 '8.7',
 '8.5',
 '9.2',
 '9.4',
 '9.4',
 '8.1',
 '9.2',
 '9.5',
 '8.8',
 '8.7',
 '9.0',
 '9.2',
 '9.7',
 '9.6',
 '9.3',
 '9.0',
 '9.4',
 '9.6',
 '8.8',
 '9.0',
 '9.1',
 '9.3',
 '8.6',
 '9.0',
 '8.9',
 '9.4',
 '9.5',
 '8.9',
 '8.9',
 '9.1',
 '7.9',
 '9.8',
 '9.4',
 '9.2',
 '9.4',
 '8.9',
 '8.6',
 '9.1',
 '9.4',
 '9.5',
 '9.2',
 '8.7',
 '8.5',
 '9.2',
 '9.7',
 '9.4',
 '9.3',
 '9.5',
 '9.4',
 '9.1',
 '9.6',
 '9.5',
 '9.4',
 '9.1',
 '9.2',
 '9.6',
 '8.7',
 '7.9',
 '8.7',
 '8.7',
 '8.1',
 '8.2',
 '8.9',
 '8.9',
 '9.6',
 '9.0',
 '9.3',
 '9.6',
 '9.3',
 '9.3',
 '9.3',
 '9.5',
 '8.9',
 '8.8',
 '8.8',
 '9.6',
 '9.2',
 '9.7',
 '8.6',
 '8.7',
 '9.2',
 '9.2',
 '9.2',
 '9.3',
 '9.3',
 '9.5',
 '9.5',
 '8.9',
 '9.1',
 '8.7',
 '9.6',
 '9.3',
 '9.6',
 '8.7',
 '8.7',
 '8.9',
 '9.2',
 '9.5',
 '9.3',
 '9.3',
 '9.4',
 '9.3',
 '8.9',
 '9.2',
 '9.5',
 '7.6',
 '9.6',
 '9.7',
 '8.0',
 '9.4',
 '9.5',
 '9.2',
 '9.3',
 '8.8',
 '9.4',
 '9.5',
 '9.5',
 '9.1',
 '9.7',
 '9.4',
 '9.1',
 '8.9',
 '9.3',
 '9.1',
 '9.4',
 '9.5',
 '9.1',
 '9.6',
 '9.0',
 '8.5',
 '9.2',
 '9.3',
 '9.0',
 '9.6',
 '9.5',
 '9.4',
 '9.3',
 '9.2',
 '9.3',
 '9.5',
 '8.1',
 '9.2',
 '9.4',
 '9.5',
 '9.4',
 '8.6',
 '9.6',
 '9.2',
 '9.2',
 '9.2',
 '9.2',
 '8.9',
 '9.6',
 '9.3',
 '9.0',
 '9.6',
 '9.0',
 '9.2',
 '9.3',
 '9.4',
 '8.7',
 '9.6',
 '9.3',
 '8.9',
 '9.3',
 '9.5',
 '9.5',
 '9.0',
 '9.5',
 '9.2',
 '8.8',
 '9.6',
 '8.7',
 '8.3',
 '9.3',
 '8.4',
 '9.1',
 '8.3',
 '9.6',
 '9.6',
 '8.9',
 '9.5',
 '9.5',
 '8.8',
 '9.0',
 '9.6',
 '9.6',
 '9.6',
 '8.7',
 '8.5',
 '9.5',
 '9.6',
 '8.2',
 '9.1',
 '9.3',
 '8.6',
 '9.3',
 '9.5',
 '9.1',
 '9.2',
 '9.6',
 '9.6',
 '8.8',
 '8.8',
 '9.1',
 '9.0',
 '9.3',
 '9.1',
 '9.7',
 '9.0',
 '9.1',
 '9.2',
 '9.6',
 '9.4',
 '9.0',
 '9.7',
 '9.4',
 '9.3',
 '9.2',
 '9.1',
 '8.9',
 '9.3',
 '9.7',
 '9.4',
 '8.9',
 '9.3',
 '8.8',
 '9.0',
 '9.1',
 '9.3',
 '9.2',
 '9.5',
 '8.8',
 '9.7',
 '9.4',
 '9.2',
 '9.0',
 '8.9',
 '8.6',
 '9.1',
 '9.0',
 '9.6',
 '9.4',
 '9.3',
 '9.5',
 '9.6',
 '9.1',
 '7.3',
 '9.5',
 '8.2',
 '9.0',
 '8.4',
 '9.4',
 '9.5',
 '8.5',
 '9.5',
 '8.8',
 '9.3',
 '9.5',
 '8.1',
 '8.7',
 '9.1',
 '9.2',
 '9.3',
 '9.3',
 '8.7',
 '9.5',
 '9.6',
 '9.1',
 '9.0',
 '9.3',
 '9.1',
 '8.2',
 '8.6',
 '9.5',
 '9.4',
 '9.3',
 '8.9',
 '8.9',
 '9.3',
 '9.1',
 '7.9',
 '9.7',
 '8.8',
 '9.1',
 '9.1',
 '9.4',
 '9.4',
 '9.7',
 '9.1',
 '8.4',
 '9.3',
 '9.2',
 '9.6',
 '9.2',
 '9.3',
 '9.1',
 '8.9',
 '9.0',
 '9.2',
 '8.8',
 '9.2',
 '9.4',
 '9.4',
 '9.4',
 '8.2',
 '9.3',
 '9.3',
 '9.1',
 '9.4',
 '9.3',
 '9.4',
 '8.8',
 '9.0',
 '7.6',
 '9.3',
 '8.3',
 '9.4',
 '8.9',
 '9.4',
 '9.3',
 '9.3',
 '9.7',
 '9.5',
 '9.6',
 '9.4',
 '9.2',
 '9.3',
 '9.5',
 '9.3',
 '9.5',
 '9.3',
 '9.3',
 '9.2',
 '8.2',
 '8.5',
 '9.7',
 '9.6',
 '9.2',
 '9.3',
 '8.3',
 '8.6',
 '9.0',
 '9.6',
 '8.7',
 '9.1',
 '9.1',
 '9.6',
 '9.5',
 '9.4',
 '9.2',
 '8.8',
 '9.5',
 '9.4',
 '9.0',
 '9.1',
 '9.4',
 '9.2',
 '9.4',
 '7.8',
 '9.5',
 '9.1',
 '7.4',
 '9.2',
 '9.0',
 '9.3',
 '8.6',
 '8.9',
 '9.5',
 '9.5',
 '9.6',
 '9.1',
 '9.1',
 '7.7',
 '7.7',
 '9.7',
 '8.3',
 '9.1',
 '9.2',
 '9.4',
 '9.3',
 '9.0',
 '9.2',
 '9.6',
 '7.7',
 '8.6',
 '9.6',
 '9.4',
 '9.3',
 '8.8',
 '9.0',
 '9.1',
 '9.0',
 '8.2',
 '8.8',
 '9.5',
 '8.8',
 '9.4',
 '9.4',
 '9.3',
 '9.2',
 '9.2',
 '9.2',
 '9.4',
 '9.4',
 '9.6',
 '8.6',
 '9.6',
 '9.2',
 '8.5',
 '8.4',
 '9.3',
 '7.5',
 '9.4',
 '9.5',
 '9.3',
 '8.2',
 '8.9',
 '9.4',
 '9.0',
 '9.3',
 '8.8',
 '8.3',
 '8.6',
 '9.0',
 '9.0',
 '8.4',
 '9.6',
 '8.4',
 '9.5',
 '8.8',
 '9.4',
 '9.3',
 '9.4',
 '9.2',
 '8.9',
 '9.2',
 '9.4',
 '9.6',
 '9.3',
 '9.6',
 '8.2',
 '9.1',
 '8.2',
 '8.5',
 '9.3',
 '8.5',
 '9.2',
 '9.4',
 '9.5',
 '9.3',
 '9.2',
 '7.6',
 '8.7',
 '9.1',
 '9.2',
 '9.6',
 '9.2',
 '9.2',
 '8.9',
 '9.6',
 '7.7',
 '9.3',
 '9.4',
 '9.2',
 '8.6',
 '9.5',
 '8.8',
 '9.5',
 '8.3',
 '8.8',
 '9.4',
 '7.9',
 '9.6',
 '9.2',
 '9.2',
 '8.3',
 '9.4',
 '9.2',
 '9.5',
 '9.3',
 ...]

In [ ]:
df['User-Rating'] = 1
df

/tmp/ipykernel_1411/3111194552.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['User-Rating'] = 1

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,"Kumar Sanu, Mika Singh, Neha Kakkar",BollywoodDance,Simmba,1
1,Coca Cola,"Neha Kakkar, Tony Kakkar",BollywoodDanceRomantic,Luka Chuppi,1
2,Apna Time Aayega,Ranveer Singh,BollywoodDance,Gully Boy,1
3,Mungda,"Jyotica Tangri, Shaan, Subhro Ganguly",BollywoodDance,Total Dhamaal,1
4,Tere Bin,"Asees Kaur, Rahat Fateh Ali Khan, Tanishk Bagchi",BollywoodRomantic,Simmba,1
...,...,...,...,...,...
2415,Jana Tumhare Pyar Mein,Mukesh,BollywoodDance,Sasural,1
2416,Tum Jaise Bigde Babu Se,Lata Mangeshkar,BollywoodDance,Jab Pyar Kisi Se Hota Hai,1
2417,O Yaad Nahi Bhool Gaya,"Lata Mangeshkar, Suresh Wadkar",BollywoodDance,Lamhe,1
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,Jagjit Kaur,BollywoodDance,Shola Aur Shabnam,1
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,Asha Bhosle,BollywoodDance,Shola Aur Shabnam,1

In [ ]:
df['Album/Movie'] = df['Album/Movie'].str.replace(' ', ',')
df['Singer/Artists'] = df['Singer/Artists'].str.replace(' ', '')
df

/tmp/ipykernel_1411/1607997639.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Album/Movie'] = df['Album/Movie'].str.replace(' ', ',')
/tmp/ipykernel_1411/1607997639.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Singer/Artists'] = df['Singer/Artists'].str.replace(' ', '')

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,"KumarSanu,MikaSingh,NehaKakkar",BollywoodDance,Simmba,1
1,Coca Cola,"NehaKakkar,TonyKakkar",BollywoodDanceRomantic,"Luka,Chuppi",1
2,Apna Time Aayega,RanveerSingh,BollywoodDance,"Gully,Boy",1
3,Mungda,"JyoticaTangri,Shaan,SubhroGanguly",BollywoodDance,"Total,Dhamaal",1
4,Tere Bin,"AseesKaur,RahatFatehAliKhan,TanishkBagchi",BollywoodRomantic,Simmba,1
...,...,...,...,...,...
2415,Jana Tumhare Pyar Mein,Mukesh,BollywoodDance,Sasural,1
2416,Tum Jaise Bigde Babu Se,LataMangeshkar,BollywoodDance,"Jab,Pyar,Kisi,Se,Hota,Hai",1
2417,O Yaad Nahi Bhool Gaya,"LataMangeshkar,SureshWadkar",BollywoodDance,Lamhe,1
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,JagjitKaur,BollywoodDance,"Shola,Aur,Shabnam",1
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,AshaBhosle,BollywoodDance,"Shola,Aur,Shabnam",1

In [ ]:
df['Singer/Artists'] = df['Singer/Artists'].str.replace(',', '')
df

/tmp/ipykernel_1411/2181200074.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Singer/Artists'] = df['Singer/Artists'].str.replace(',', '')

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating
0,Aankh Marey,KumarSanuMikaSinghNehaKakkar,BollywoodDance,Simmba,1
1,Coca Cola,NehaKakkarTonyKakkar,BollywoodDanceRomantic,"Luka,Chuppi",1
2,Apna Time Aayega,RanveerSingh,BollywoodDance,"Gully,Boy",1
3,Mungda,JyoticaTangriShaanSubhroGanguly,BollywoodDance,"Total,Dhamaal",1
4,Tere Bin,AseesKaurRahatFatehAliKhanTanishkBagchi,BollywoodRomantic,Simmba,1
...,...,...,...,...,...
2415,Jana Tumhare Pyar Mein,Mukesh,BollywoodDance,Sasural,1
2416,Tum Jaise Bigde Babu Se,LataMangeshkar,BollywoodDance,"Jab,Pyar,Kisi,Se,Hota,Hai",1
2417,O Yaad Nahi Bhool Gaya,LataMangeshkarSureshWadkar,BollywoodDance,Lamhe,1
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,JagjitKaur,BollywoodDance,"Shola,Aur,Shabnam",1
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,AshaBhosle,BollywoodDance,"Shola,Aur,Shabnam",1

In [ ]:

df['tags'] = df['Singer/Artists'] + ' ' + df['Genre'] + ' ' + df['Album/Movie'] + ' ' + df['User-Rating']
df['tags']

/tmp/ipykernel_1411/1496932513.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['Singer/Artists'] + ' ' + df['Genre'] + ' ' + df['Album/Movie'] + ' ' + df['User-Rating']

0       KumarSanuMikaSinghNehaKakkar BollywoodDance Si...
1       NehaKakkarTonyKakkar BollywoodDanceRomantic Lu...
2                 RanveerSingh BollywoodDance Gully,Boy 1
3       JyoticaTangriShaanSubhroGanguly BollywoodDance...
4       AseesKaurRahatFatehAliKhanTanishkBagchi Bollyw...
                              ...
2415                      Mukesh BollywoodDance Sasural 1
2416    LataMangeshkar BollywoodDance Jab,Pyar,Kisi,Se...
2417    LataMangeshkarSureshWadkar BollywoodDance Lamhe 1
2418        JagjitKaur BollywoodDance Shola,Aur,Shabnam 1
2419        AshaBhosle BollywoodDance Shola,Aur,Shabnam 1
Name: tags, Length: 2391, dtype: object

In [ ]:

df['tags'] = df['Singer/Artists'] + ' ' + df['Genre'] + ' ' + df['Album/Movie'] + ' ' + df['User-Rating']
df['tags'][0]

/tmp/ipykernel_1411/1829045188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['tags'] = df['Singer/Artists'] + ' ' + df['Genre'] + ' ' + df['Album/Movie'] + ' ' + df['User-Rating']

'KumarSanuMikaSinghNehaKakkar BollywoodDance Simmba 1'

In [ ]:
new_df = df[['Song-Name', 'tags']]
new_df

,Song-Name,tags
0,Aankh Marey,KumarSanuMikaSinghNehaKakkar BollywoodDance Si...
1,Coca Cola,NehaKakkarTonyKakkar BollywoodDanceRomantic Lu...
2,Apna Time Aayega,"RanveerSingh BollywoodDance Gully,Boy 1"
3,Mungda,JyoticaTangriShaanSubhroGanguly BollywoodDance...
4,Tere Bin,AseesKaurRahatFatehAliKhanTanishkBagchi Bollyw...
...,...,...
2415,Jana Tumhare Pyar Mein,Mukesh BollywoodDance Sasural 1
2416,Tum Jaise Bigde Babu Se,"LataMangeshkar BollywoodDance Jab,Pyar,Kisi,Se..."
2417,O Yaad Nahi Bhool Gaya,LataMangeshkarSureshWadkar BollywoodDance Lamhe 1
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,"JagjitKaur BollywoodDance Shola,Aur,Shabnam 1"
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,"AshaBhosle BollywoodDance Shola,Aur,Shabnam 1"

In [ ]:
new_df['tags'] = new_df['tags'].apply(lambda x: str(x).lower())
new_df

/tmp/ipykernel_1411/2079407482.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: str(x).lower())

,Song-Name,tags
0,Aankh Marey,kumarsanumikasinghnehakakkar bollywooddance si...
1,Coca Cola,nehakakkartonykakkar bollywooddanceromantic lu...
2,Apna Time Aayega,"ranveersingh bollywooddance gully,boy 1"
3,Mungda,jyoticatangrishaansubhroganguly bollywooddance...
4,Tere Bin,aseeskaurrahatfatehalikhantanishkbagchi bollyw...
...,...,...
2415,Jana Tumhare Pyar Mein,mukesh bollywooddance sasural 1
2416,Tum Jaise Bigde Babu Se,"latamangeshkar bollywooddance jab,pyar,kisi,se..."
2417,O Yaad Nahi Bhool Gaya,latamangeshkarsureshwadkar bollywooddance lamhe 1
2418,Ladi Re Ladi Tujhse Aankh Jo Ladi,"jagjitkaur bollywooddance shola,aur,shabnam 1"
2419,Mummy Aur Daddy Mein Ladai Ho Gayi,"ashabhosle bollywooddance shola,aur,shabnam 1"

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000)

In [ ]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [ ]:
vectors.shape

(2391, 2000)

In [ ]:
cv.get_feature_names_out()

array(['10', '13', '1920', ..., 'zinda', 'zindagi', 'zubeengarg'],
      dtype=object)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [ ]:
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x: x[1])

[(0, np.float64(1.0000000000000002)),
 (515, np.float64(0.5773502691896258)),
 (956, np.float64(0.5773502691896258)),
 (2176, np.float64(0.5773502691896258)),
 (23, np.float64(0.408248290463863)),
 (56, np.float64(0.408248290463863)),
 (62, np.float64(0.408248290463863)),
 (75, np.float64(0.408248290463863)),
 (78, np.float64(0.408248290463863)),
 (223, np.float64(0.408248290463863)),
 (252, np.float64(0.408248290463863)),
 (257, np.float64(0.408248290463863)),
 (340, np.float64(0.408248290463863)),
 (372, np.float64(0.408248290463863)),
 (393, np.float64(0.408248290463863)),
 (417, np.float64(0.408248290463863)),
 (433, np.float64(0.408248290463863)),
 (434, np.float64(0.408248290463863)),
 (468, np.float64(0.408248290463863)),
 (476, np.float64(0.408248290463863)),
 (513, np.float64(0.408248290463863)),
 (524, np.float64(0.408248290463863)),
 (553, np.float64(0.408248290463863)),
 (572, np.float64(0.408248290463863)),
 (580, np.float64(0.408248290463863)),
 (593, np.float64(0.408248290463863)),
 (631, np.float64(0.408248290463863)),
 (632, np.float64(0.408248290463863)),
 (659, np.float64(0.408248290463863)),
 (740, np.float64(0.408248290463863)),
 (792, np.float64(0.408248290463863)),
 (846, np.float64(0.408248290463863)),
 (880, np.float64(0.408248290463863)),
 (932, np.float64(0.408248290463863)),
 (982, np.float64(0.408248290463863)),
 (997, np.float64(0.408248290463863)),
 (1017, np.float64(0.408248290463863)),
 (1059, np.float64(0.408248290463863)),
 (1090, np.float64(0.408248290463863)),
 (1118, np.float64(0.408248290463863)),
 (1138, np.float64(0.408248290463863)),
 (1187, np.float64(0.408248290463863)),
 (1190, np.float64(0.408248290463863)),
 (1196, np.float64(0.408248290463863)),
 (1208, np.float64(0.408248290463863)),
 (1217, np.float64(0.408248290463863)),
 (1236, np.float64(0.408248290463863)),
 (1391, np.float64(0.408248290463863)),
 (1392, np.float64(0.408248290463863)),
 (1454, np.float64(0.408248290463863)),
 (1479, np.float64(0.408248290463863)),
 (1498, np.float64(0.408248290463863)),
 (1512, np.float64(0.408248290463863)),
 (1524, np.float64(0.408248290463863)),
 (1542, np.float64(0.408248290463863)),
 (1562, np.float64(0.408248290463863)),
 (1568, np.float64(0.408248290463863)),
 (1608, np.float64(0.408248290463863)),
 (1611, np.float64(0.408248290463863)),
 (1647, np.float64(0.408248290463863)),
 (1652, np.float64(0.408248290463863)),
 (1769, np.float64(0.408248290463863)),
 (1806, np.float64(0.408248290463863)),
 (1821, np.float64(0.408248290463863)),
 (1859, np.float64(0.408248290463863)),
 (1873, np.float64(0.408248290463863)),
 (1874, np.float64(0.408248290463863)),
 (1889, np.float64(0.408248290463863)),
 (1918, np.float64(0.408248290463863)),
 (1931, np.float64(0.408248290463863)),
 (1945, np.float64(0.408248290463863)),
 (1952, np.float64(0.408248290463863)),
 (1967, np.float64(0.408248290463863)),
 (1979, np.float64(0.408248290463863)),
 (1990, np.float64(0.408248290463863)),
 (2007, np.float64(0.408248290463863)),
 (2045, np.float64(0.408248290463863)),
 (2048, np.float64(0.408248290463863)),
 (2066, np.float64(0.408248290463863)),
 (2123, np.float64(0.408248290463863)),
 (2130, np.float64(0.408248290463863)),
 (2177, np.float64(0.408248290463863)),
 (2195, np.float64(0.408248290463863)),
 (2206, np.float64(0.408248290463863)),
 (2241, np.float64(0.408248290463863)),
 (2283, np.float64(0.408248290463863)),
 (2308, np.float64(0.408248290463863)),
 (2318, np.float64(0.408248290463863)),
 (2324, np.float64(0.408248290463863)),
 (2367, np.float64(0.408248290463863)),
 (2368, np.float64(0.408248290463863)),
 (2375, np.float64(0.408248290463863)),
 (2382, np.float64(0.408248290463863)),
 (2385, np.float64(0.408248290463863)),
 (3, np.float64(0.3333333333333334)),
 (4, np.float64(0.3333333333333334)),
 (5, np.float64(0.3333333333333334)),
 (6, np.float64(0.3333333333333334)),
 (8, np.float64(0.3333333333333334)),
 (14, np.float64(0.3333333333333334)),
 (17, np.float64(0.3333333333333334)),
 (19, np.float64(0.3333333333333334)),
 (21, np.float64(0.3333333333333334)),
 (27, np.float64(0.3333333333333334)),
 (31, np.float64(0.3333333333333334)),
 (34, np.float64(0.3333333333333334)),
 (37, np.float64(0.3333333333333334)),
 (38, np.float64(0.3333333333333334)),
 (40, np.float64(0.3333333333333334)),
 (41, np.float64(0.3333333333333334)),
 (42, np.float64(0.3333333333333334)),
 (47, np.float64(0.3333333333333334)),
 (51, np.float64(0.3333333333333334)),
 (53, np.float64(0.3333333333333334)),
 (54, np.float64(0.3333333333333334)),
 (55, np.float64(0.3333333333333334)),
 (63, np.float64(0.3333333333333334)),
 (68, np.float64(0.3333333333333334)),
 (76, np.float64(0.3333333333333334)),
 (89, np.float64(0.3333333333333334)),
 (103, np.float64(0.3333333333333334)),
 (108, np.float64(0.3333333333333334)),
 (111, np.float64(0.3333333333333334)),
 (115, np.float64(0.3333333333333334)),
 (117, np.float64(0.3333333333333334)),
 (120, np.float64(0.3333333333333334)),
 (123, np.float64(0.3333333333333334)),
 (126, np.float64(0.3333333333333334)),
 (130, np.float64(0.3333333333333334)),
 (136, np.float64(0.3333333333333334)),
 (142, np.float64(0.3333333333333334)),
 (148, np.float64(0.3333333333333334)),
 (150, np.float64(0.3333333333333334)),
 (161, np.float64(0.3333333333333334)),
 (173, np.float64(0.3333333333333334)),
 (176, np.float64(0.3333333333333334)),
 (177, np.float64(0.3333333333333334)),
 (179, np.float64(0.3333333333333334)),
 (181, np.float64(0.3333333333333334)),
 (194, np.float64(0.3333333333333334)),
 (195, np.float64(0.3333333333333334)),
 (197, np.float64(0.3333333333333334)),
 (208, np.float64(0.3333333333333334)),
 (211, np.float64(0.3333333333333334)),
 (216, np.float64(0.3333333333333334)),
 (232, np.float64(0.3333333333333334)),
 (260, np.float64(0.3333333333333334)),
 (268, np.float64(0.3333333333333334)),
 (288, np.float64(0.3333333333333334)),
 (289, np.float64(0.3333333333333334)),
 (293, np.float64(0.3333333333333334)),
 (300, np.float64(0.3333333333333334)),
 (303, np.float64(0.3333333333333334)),
 (310, np.float64(0.3333333333333334)),
 (313, np.float64(0.3333333333333334)),
 (318, np.float64(0.3333333333333334)),
 (323, np.float64(0.3333333333333334)),
 (334, np.float64(0.3333333333333334)),
 (338, np.float64(0.3333333333333334)),
 (343, np.float64(0.3333333333333334)),
 (357, np.float64(0.3333333333333334)),
 (368, np.float64(0.3333333333333334)),
 (375, np.float64(0.3333333333333334)),
 (379, np.float64(0.3333333333333334)),
 (385, np.float64(0.3333333333333334)),
 (387, np.float64(0.3333333333333334)),
 (400, np.float64(0.3333333333333334)),
 (406, np.float64(0.3333333333333334)),
 (411, np.float64(0.3333333333333334)),
 (414, np.float64(0.3333333333333334)),
 (421, np.float64(0.3333333333333334)),
 (428, np.float64(0.3333333333333334)),
 (432, np.float64(0.3333333333333334)),
 (435, np.float64(0.3333333333333334)),
 (440, np.float64(0.3333333333333334)),
 (453, np.float64(0.3333333333333334)),
 (454, np.float64(0.3333333333333334)),
 (459, np.float64(0.3333333333333334)),
 (470, np.float64(0.3333333333333334)),
 (478, np.float64(0.3333333333333334)),
 (484, np.float64(0.3333333333333334)),
 (487, np.float64(0.3333333333333334)),
 (489, np.float64(0.3333333333333334)),
 (496, np.float64(0.3333333333333334)),
 (500, np.float64(0.3333333333333334)),
 (504, np.float64(0.3333333333333334)),
 (505, np.float64(0.3333333333333334)),
 (508, np.float64(0.3333333333333334)),
 (510, np.float64(0.3333333333333334)),
 (511, np.float64(0.3333333333333334)),
 (525, np.float64(0.3333333333333334)),
 (528, np.float64(0.3333333333333334)),
 (530, np.float64(0.3333333333333334)),
 (533, np.float64(0.3333333333333334)),
 (539, np.float64(0.3333333333333334)),
 (540, np.float64(0.3333333333333334)),
 (554, np.float64(0.3333333333333334)),
 (561, np.float64(0.3333333333333334)),
 (565, np.float64(0.3333333333333334)),
 (571, np.float64(0.3333333333333334)),
 (581, np.float64(0.3333333333333334)),
 (584, np.float64(0.3333333333333334)),
 (589, np.float64(0.3333333333333334)),
 (591, np.float64(0.3333333333333334)),
 (597, np.float64(0.3333333333333334)),
 (599, np.float64(0.3333333333333334)),
 (600, np.float64(0.3333333333333334)),
 (606, np.float64(0.3333333333333334)),
 (607, np.float64(0.3333333333333334)),
 (608, np.float64(0.3333333333333334)),
 (609, np.float64(0.3333333333333334)),
 (611, np.float64(0.3333333333333334)),
 (612, np.float64(0.3333333333333334)),
 (614, np.float64(0.3333333333333334)),
 (629, np.float64(0.3333333333333334)),
 (633, np.float64(0.3333333333333334)),
 (639, np.float64(0.3333333333333334)),
 (640, np.float64(0.3333333333333334)),
 (648, np.float64(0.3333333333333334)),
 (661, np.float64(0.3333333333333334)),
 (663, np.float64(0.3333333333333334)),
 (676, np.float64(0.3333333333333334)),
 (677, np.float64(0.3333333333333334)),
 (686, np.float64(0.3333333333333334)),
 (687, np.float64(0.3333333333333334)),
 (689, np.float64(0.3333333333333334)),
 (696, np.float64(0.3333333333333334)),
 (711, np.float64(0.3333333333333334)),
 (713, np.float64(0.3333333333333334)),
 (717, np.float64(0.3333333333333334)),
 (721, np.float64(0.3333333333333334)),
 (722, np.float64(0.3333333333333334)),
 (723, np.float64(0.3333333333333334)),
 (726, np.float64(0.3333333333333334)),
 (729, np.float64(0.3333333333333334)),
 (730, np.float64(0.3333333333333334)),
 (736, np.float64(0.3333333333333334)),
 (756, np.float64(0.3333333333333334)),
 (758, np.float64(0.3333333333333334)),
 (766, np.float64(0.3333333333333334)),
 (773, np.float64(0.3333333333333334)),
 (775, np.float64(0.3333333333333334)),
 (780, np.float64(0.3333333333333334)),
 (787, np.float64(0.3333333333333334)),
 (789, np.float64(0.3333333333333334)),
 (799, np.float64(0.3333333333333334)),
 (811, np.float64(0.3333333333333334)),
 (815, np.float64(0.3333333333333334)),
 (817, np.float64(0.3333333333333334)),
 (821, np.float64(0.3333333333333334)),
 (822, np.float64(0.3333333333333334)),
 (825, np.float64(0.3333333333333334)),
 (831, np.float64(0.3333333333333334)),
 (833, np.float64(0.3333333333333334)),
 (838, np.float64(0.3333333333333334)),
 (840, np.float64(0.3333333333333334)),
 (845, np.float64(0.3333333333333334)),
 (852, np.float64(0.3333333333333334)),
 (853, np.float64(0.3333333333333334)),
 (873, np.float64(0.3333333333333334)),
 (877, np.float64(0.3333333333333334)),
 (881, np.float64(0.3333333333333334)),
 (886, np.float64(0.3333333333333334)),
 (889, np.float64(0.3333333333333334)),
 (891, np.float64(0.3333333333333334)),
 (901, np.float64(0.3333333333333334)),
 (919, np.float64(0.3333333333333334)),
 (940, np.float64(0.3333333333333334)),
 (947, np.float64(0.3333333333333334)),
 (953, np.float64(0.3333333333333334)),
 (958, np.float64(0.3333333333333334)),
 (960, np.float64(0.3333333333333334)),
 (971, np.float64(0.3333333333333334)),
 (985, np.float64(0.3333333333333334)),
 (1002, np.float64(0.3333333333333334)),
 (1003, np.float64(0.3333333333333334)),
 (1005, np.float64(0.3333333333333334)),
 (1024, np.float64(0.3333333333333334)),
 (1026, np.float64(0.3333333333333334)),
 (1027, np.float64(0.3333333333333334)),
 (1031, np.float64(0.3333333333333334)),
 (1033, np.float64(0.3333333333333334)),
 (1034, np.float64(0.3333333333333334)),
 (1038, np.float64(0.3333333333333334)),
 (1046, np.float64(0.3333333333333334)),
 (1054, np.float64(0.3333333333333334)),
 (1057, np.float64(0.3333333333333334)),
 (1060, np.float64(0.3333333333333334)),
 (1069, np.float64(0.3333333333333334)),
 (1074, np.float64(0.3333333333333334)),
 (1076, np.float64(0.3333333333333334)),
 (1078, np.float64(0.3333333333333334)),
 (1080, np.float64(0.3333333333333334)),
 (1083, np.float64(0.3333333333333334)),
 (1088, np.float64(0.3333333333333334)),
 (1092, np.float64(0.3333333333333334)),
 (1097, np.float64(0.3333333333333334)),
 (1104, np.float64(0.3333333333333334)),
 (1107, np.float64(0.3333333333333334)),
 (1113, np.float64(0.3333333333333334)),
 (1116, np.float64(0.3333333333333334)),
 (1119, np.float64(0.3333333333333334)),
 (1120, np.float64(0.3333333333333334)),
 (1124, np.float64(0.3333333333333334)),
 (1141, np.float64(0.3333333333333334)),
 (1170, np.float64(0.3333333333333334)),
 (1177, np.float64(0.3333333333333334)),
 (1183, np.float64(0.3333333333333334)),
 (1198, np.float64(0.3333333333333334)),
 (1199, np.float64(0.3333333333333334)),
 (1200, np.float64(0.3333333333333334)),
 (1210, np.float64(0.3333333333333334)),
 (1211, np.float64(0.3333333333333334)),
 (1212, np.float64(0.3333333333333334)),
 (1223, np.float64(0.3333333333333334)),
 (1238, np.float64(0.3333333333333334)),
 (1239, np.float64(0.3333333333333334)),
 (1241, np.float64(0.3333333333333334)),
 (1243, np.float64(0.3333333333333334)),
 (1247, np.float64(0.3333333333333334)),
 (1250, np.float64(0.3333333333333334)),
 (1251, np.float64(0.3333333333333334)),
 (1252, np.float64(0.3333333333333334)),
 (1254, np.float64(0.3333333333333334)),
 (1255, np.float64(0.3333333333333334)),
 (1259, np.float64(0.3333333333333334)),
 (1268, np.float64(0.3333333333333334)),
 (1274, np.float64(0.3333333333333334)),
 (1277, np.float64(0.3333333333333334)),
 (1279, np.float64(0.3333333333333334)),
 (1282, np.float64(0.3333333333333334)),
 (1287, np.float64(0.3333333333333334)),
 (1289, np.float64(0.3333333333333334)),
 (1290, np.float64(0.3333333333333334)),
 (1294, np.float64(0.3333333333333334)),
 (1295, np.float64(0.3333333333333334)),
 (1297, np.float64(0.3333333333333334)),
 (1304, np.float64(0.3333333333333334)),
 (1306, np.float64(0.3333333333333334)),
 (1308, np.float64(0.3333333333333334)),
 (1309, np.float64(0.3333333333333334)),
 (1315, np.float64(0.3333333333333334)),
 (1318, np.float64(0.3333333333333334)),
 (1323, np.float64(0.3333333333333334)),
 (1329, np.float64(0.3333333333333334)),
 (1332, np.float64(0.3333333333333334)),
 (1333, np.float64(0.3333333333333334)),
 (1335, np.float64(0.3333333333333334)),
 (1353, np.float64(0.3333333333333334)),
 (1355, np.float64(0.3333333333333334)),
 (1360, np.float64(0.3333333333333334)),
 (1364, np.float64(0.3333333333333334)),
 (1366, np.float64(0.3333333333333334)),
 (1379, np.float64(0.3333333333333334)),
 (1381, np.float64(0.3333333333333334)),
 (1384, np.float64(0.3333333333333334)),
 (1388, np.float64(0.3333333333333334)),
 (1396, np.float64(0.3333333333333334)),
 (1398, np.float64(0.3333333333333334)),
 (1399, np.float64(0.3333333333333334)),
 (1405, np.float64(0.3333333333333334)),
 (1410, np.float64(0.3333333333333334)),
 (1414, np.float64(0.3333333333333334)),
 (1419, np.float64(0.3333333333333334)),
 (1420, np.float64(0.3333333333333334)),
 (1428, np.float64(0.3333333333333334)),
 (1433, np.float64(0.3333333333333334)),
 (1436, np.float64(0.3333333333333334)),
 (1437, np.float64(0.3333333333333334)),
 (1442, np.float64(0.3333333333333334)),
 (1462, np.float64(0.3333333333333334)),
 (1478, np.float64(0.3333333333333334)),
 (1495, np.float64(0.3333333333333334)),
 (1499, np.float64(0.3333333333333334)),
 (1507, np.float64(0.3333333333333334)),
 (1508, np.float64(0.3333333333333334)),
 (1514, np.float64(0.3333333333333334)),
 (1517, np.float64(0.3333333333333334)),
 (1522, np.float64(0.3333333333333334)),
 (1523, np.float64(0.3333333333333334)),
 (1528, np.float64(0.3333333333333334)),
 (1529, np.float64(0.3333333333333334)),
 (1530, np.float64(0.3333333333333334)),
 (1539, np.float64(0.3333333333333334)),
 (1540, np.float64(0.3333333333333334)),
 (1543, np.float64(0.3333333333333334)),
 (1546, np.float64(0.3333333333333334)),
 (1555, np.float64(0.3333333333333334)),
 (1559, np.float64(0.3333333333333334)),
 (1563, np.float64(0.3333333333333334)),
 (1571, np.float64(0.3333333333333334)),
 (1572, np.float64(0.3333333333333334)),
 (1576, np.float64(0.3333333333333334)),
 (1580, np.float64(0.3333333333333334)),
 (1582, np.float64(0.3333333333333334)),
 (1594, np.float64(0.3333333333333334)),
 (1597, np.float64(0.3333333333333334)),
 (1605, np.float64(0.3333333333333334)),
 (1610, np.float64(0.3333333333333334)),
 (1613, np.float64(0.3333333333333334)),
 (1614, np.float64(0.3333333333333334)),
 (1624, np.float64(0.3333333333333334)),
 (1625, np.float64(0.3333333333333334)),
 (1631, np.float64(0.3333333333333334)),
 (1634, np.float64(0.3333333333333334)),
 (1642, np.float64(0.3333333333333334)),
 (1645, np.float64(0.3333333333333334)),
 (1649, np.float64(0.3333333333333334)),
 (1654, np.float64(0.3333333333333334)),
 (1667, np.float64(0.3333333333333334)),
 (1668, np.float64(0.3333333333333334)),
 (1678, np.float64(0.3333333333333334)),
 (1682, np.float64(0.3333333333333334)),
 (1684, np.float64(0.3333333333333334)),
 (1686, np.float64(0.3333333333333334)),
 (1694, np.float64(0.3333333333333334)),
 (1696, np.float64(0.3333333333333334)),
 (1699, np.float64(0.3333333333333334)),
 (1707, np.float64(0.3333333333333334)),
 (1717, np.float64(0.3333333333333334)),
 (1723, np.float64(0.3333333333333334)),
 (1724, np.float64(0.3333333333333334)),
 (1725, np.float64(0.3333333333333334)),
 (1726, np.float64(0.3333333333333334)),
 (1743, np.float64(0.3333333333333334)),
 (1749, np.float64(0.3333333333333334)),
 (1754, np.float64(0.3333333333333334)),
 (1757, np.float64(0.3333333333333334)),
 (1758, np.float64(0.3333333333333334)),
 (1763, np.float64(0.3333333333333334)),
 (1767, np.float64(0.3333333333333334)),
 (1771, np.float64(0.3333333333333334)),
 (1782, np.float64(0.3333333333333334)),
 (1786, np.float64(0.3333333333333334)),
 (1791, np.float64(0.3333333333333334)),
 (1793, np.float64(0.3333333333333334)),
 (1808, np.float64(0.3333333333333334)),
 (1809, np.float64(0.3333333333333334)),
 (1815, np.float64(0.3333333333333334)),
 (1822, np.float64(0.3333333333333334)),
 (1823, np.float64(0.3333333333333334)),
 (1829, np.float64(0.3333333333333334)),
 (1830, np.float64(0.3333333333333334)),
 (1833, np.float64(0.3333333333333334)),
 (1834, np.float64(0.3333333333333334)),
 (1843, np.float64(0.3333333333333334)),
 (1855, np.float64(0.3333333333333334)),
 (1856, np.float64(0.3333333333333334)),
 (1861, np.float64(0.3333333333333334)),
 (1866, np.float64(0.3333333333333334)),
 (1872, np.float64(0.3333333333333334)),
 (1875, np.float64(0.3333333333333334)),
 (1877, np.float64(0.3333333333333334)),
 (1881, np.float64(0.3333333333333334)),
 (1882, np.float64(0.3333333333333334)),
 (1883, np.float64(0.3333333333333334)),
 (1891, np.float64(0.3333333333333334)),
 (1895, np.float64(0.3333333333333334)),
 (1898, np.float64(0.3333333333333334)),
 (1903, np.float64(0.3333333333333334)),
 (1905, np.float64(0.3333333333333334)),
 (1908, np.float64(0.3333333333333334)),
 (1915, np.float64(0.3333333333333334)),
 (1922, np.float64(0.3333333333333334)),
 (1933, np.float64(0.3333333333333334)),
 (1937, np.float64(0.3333333333333334)),
 (1944, np.float64(0.3333333333333334)),
 (1946, np.float64(0.3333333333333334)),
 (1957, np.float64(0.3333333333333334)),
 (1961, np.float64(0.3333333333333334)),
 (1962, np.float64(0.3333333333333334)),
 (1966, np.float64(0.3333333333333334)),
 (1968, np.float64(0.3333333333333334)),
 (1969, np.float64(0.3333333333333334)),
 (1970, np.float64(0.3333333333333334)),
 (1975, np.float64(0.3333333333333334)),
 (1976, np.float64(0.3333333333333334)),
 (1980, np.float64(0.3333333333333334)),
 (1981, np.float64(0.3333333333333334)),
 (1988, np.float64(0.3333333333333334)),
 (1993, np.float64(0.3333333333333334)),
 (1995, np.float64(0.3333333333333334)),
 (1997, np.float64(0.3333333333333334)),
 (1998, np.float64(0.3333333333333334)),
 (2017, np.float64(0.3333333333333334)),
 (2022, np.float64(0.3333333333333334)),
 (2035, np.float64(0.3333333333333334)),
 (2038, np.float64(0.3333333333333334)),
 (2041, np.float64(0.3333333333333334)),
 (2044, np.float64(0.3333333333333334)),
 (2050, np.float64(0.3333333333333334)),
 (2053, np.float64(0.3333333333333334)),
 (2058, np.float64(0.3333333333333334)),
 (2061, np.float64(0.3333333333333334)),
 (2062, np.float64(0.3333333333333334)),
 (2071, np.float64(0.3333333333333334)),

In [ ]:
new_df.rename(columns = {'Song-Name' : 'title'}, inplace = True)

/tmp/ipykernel_1411/2195003537.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.rename(columns = {'Song-Name' : 'title'}, inplace = True)

In [ ]:
def recommend(music):
  music_index = new_df[new_df['title'] == music].index[0]
  distances = similarity[music_index]
  music_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x : x[1])[1 : 6]
  for i in music_list:
    print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Proper Patola')

Bhare Bazaar
Dhoom Dhadakka
Tere Liye
Tu Meri Main Tera
Iski Uski

In [ ]:
df.head(50)

,Song-Name,Singer/Artists,Genre,Album/Movie,User-Rating,tags
0,Aankh Marey,KumarSanuMikaSinghNehaKakkar,BollywoodDance,Simmba,1,KumarSanuMikaSinghNehaKakkar BollywoodDance Si...
1,Coca Cola,NehaKakkarTonyKakkar,BollywoodDanceRomantic,"Luka,Chuppi",1,NehaKakkarTonyKakkar BollywoodDanceRomantic Lu...
2,Apna Time Aayega,RanveerSingh,BollywoodDance,"Gully,Boy",1,"RanveerSingh BollywoodDance Gully,Boy 1"
3,Mungda,JyoticaTangriShaanSubhroGanguly,BollywoodDance,"Total,Dhamaal",1,JyoticaTangriShaanSubhroGanguly BollywoodDance...
4,Tere Bin,AseesKaurRahatFatehAliKhanTanishkBagchi,BollywoodRomantic,Simmba,1,AseesKaurRahatFatehAliKhanTanishkBagchi Bollyw...
5,Gali Gali,NehaKakkar,BollywoodDance,KGF,1,NehaKakkar BollywoodDance KGF 1
6,Chamma Chamma,ArunIkkaNehaKakkarRomy,BollywoodDance,"Fraud,Saiyaan",1,"ArunIkkaNehaKakkarRomy BollywoodDance Fraud,Sa..."
7,Mere Gully Mein,RanveerSingh,BollywoodDance,"Gully,Boy",1,"RanveerSingh BollywoodDance Gully,Boy 1"
8,Kamariya,DarshanRaval,BollywoodDance,Mitron,1,DarshanRaval BollywoodDance Mitron 1
9,Ek Ladki Ko Dekha Toh Aisa Laga,DarshanRavalRochakKohli,BollywoodRomantic,"Ek,Ladki,Ko,Dekha,Toh,Aisa,Laga",1,"DarshanRavalRochakKohli BollywoodRomantic Ek,L..."
10,Swag Se Swagat,NehaBhasinVishalDadlani,BollywoodDance,"Tiger,Zinda,Hai",1,"NehaBhasinVishalDadlani BollywoodDance Tiger,Z..."
11,Poster Lagwa Do,MikaSinghSunandaSharma,BollywoodDance,"Luka,Chuppi",1,"MikaSinghSunandaSharma BollywoodDance Luka,Chu..."
12,Daaru Wargi,GuruRandhawa,BollywoodDance,"Cheat,India",1,"GuruRandhawa BollywoodDance Cheat,India 1"
13,Dilbar,DhvaniBhanushaliIkkaNehaKakkar,BollywoodDance,"Satyameva,Jayate",1,DhvaniBhanushaliIkkaNehaKakkar BollywoodDance ...
14,Proper Patola,AasthaGillBadshahDiljitDosanjh,BollywoodDance,"Namaste,England",1,AasthaGillBadshahDiljitDosanjh BollywoodDance ...
15,Doori,RanveerSingh,BollywoodDance,"Gully,Boy",1,"RanveerSingh BollywoodDance Gully,Boy 1"
16,Dil Diyan Gallan,AtifAslam,BollywoodRomantic,"Tiger,Zinda,Hai",1,"AtifAslam BollywoodRomantic Tiger,Zinda,Hai 1"
17,Husn Parcham,BhoomiTrivediRajaKumari,BollywoodDance,Zero,1,BhoomiTrivediRajaKumari BollywoodDance Zero 1
18,Bom Diggy Diggy,JasminWaliaZackKnight,BollywoodDance,"Sonu,Ke,Titu,Ki,Sweety",1,"JasminWaliaZackKnight BollywoodDance Sonu,Ke,T..."
19,Issaqbaazi,DivyaKumarSukhwinderSingh,BollywoodDance,Zero,1,DivyaKumarSukhwinderSingh BollywoodDance Zero 1
20,Mere Naam Tu,AbhayJodhpurkar,BollywoodRomantic,Zero,1,AbhayJodhpurkar BollywoodRomantic Zero 1
21,High Rated Gabru – Nawabzaade,GuruRandhawa,BollywoodDance,Nawabzaade,1,GuruRandhawa BollywoodDance Nawabzaade 1
22,Dekhte Dekhte,AtifAslam,BollywoodRomantic,"Batti,Gul,Meter,Chalu",1,"AtifAslam BollywoodRomantic Batti,Gul,Meter,Ch..."
23,Zingaat,AjayAtul,BollywoodDance,Dhadak,1,AjayAtul BollywoodDance Dhadak 1
24,Tareefan,Badshah,Bollywood,"Veere,Di,Wedding",1,"Badshah Bollywood Veere,Di,Wedding 1"
25,Mile Ho Tum (Reprise),NehaKakkarTonyKakkar,BollywoodRomantic,Fever,1,NehaKakkarTonyKakkar BollywoodRomantic Fever 1
26,Dil Chori,IshersSimarKaurYoYoHoneySingh,BollywoodDance,"Sonu,Ke,Titu,Ki,Sweety",1,IshersSimarKaurYoYoHoneySingh BollywoodDance S...
27,Tere Naal Nachna,BadshahSunandaSharma,BollywoodDance,Nawabzaade,1,BadshahSunandaSharma BollywoodDance Nawabzaade 1
28,Dil Meri Na Sune,AtifAslam,BollywoodRomantic,Genius,1,AtifAslam BollywoodRomantic Genius 1
29,Dhadak Title Track,AjayGogavaleShreyaGhoshal,BollywoodRomantic,Dhadak,1,AjayGogavaleShreyaGhoshal BollywoodRomantic Dh...
30,Heeriye,DeepMoneyMeetBrosNehaBhasin,BollywoodDanceRomantic,"Race,3",1,DeepMoneyMeetBrosNehaBhasin BollywoodDanceRoma...
31,Chogada,AseesKaurDarshanRaval,BollywoodDance,Loveratri,1,AseesKaurDarshanRaval BollywoodDance Loveratri 1
32,Gud Naal Ishq Mitha,HarshdeepKaurNavrajHans,BollywoodDance,"Ek,Ladki,Ko,Dekha,Toh,Aisa,Laga",1,"HarshdeepKaurNavrajHans BollywoodDance Ek,Ladk..."
33,Paniyon Sa,AtifAslamTulsiKumar,BollywoodRomantic,"Satyameva,Jayate",1,AtifAslamTulsiKumar BollywoodRomantic Satyamev...
34,Milegi Milegi,MikaSingh,BollywoodDance,Stree,1,MikaSingh BollywoodDance Stree 1
35,Morni Banke,GuruRandhawaNehaKakkar,BollywoodDance,"Badhaai,Ho",1,"GuruRandhawaNehaKakkar BollywoodDance Badhaai,..."
36,Bhare Bazaar,BPraakBadshahPayalDevVishalDadlani,BollywoodDance,"Namaste,England",1,BPraakBadshahPayalDevVishalDadlani BollywoodDa...
37,Khalibali,ShivamPathak,BollywoodDance,Padmaavat,1,ShivamPathak BollywoodDance Padmaavat 1
38,Aao Kabhi Haveli Pe,BadshahJigarNikhitaGandhiSachinSanghvi,BollywoodDance,Stree,1,BadshahJigarNikhitaGandhiSachinSanghvi Bollywo...
39,Badri Ki Dulhania,DevNegiIkkaMonaliThakurNehaKakkar,BollywoodDance,"Badrinath,Ki,Dulhania",1,DevNegiIkkaMonaliThakurNehaKakkar BollywoodDan...
40,Cheez Badi,NehaKakkarUditNarayan,BollywoodDance,Machine,1,NehaKakkarUditNarayan BollywoodDance Machine 1
41,Dholida,NehaKakkarPalakMuchchalRajaHassanUditNarayan,BollywoodDance,Loveratri,1,NehaKakkarPalakMuchchalRajaHassanUditNarayan B...
42,Sweetheart,DevNegi,BollywoodDance,Kedarnath,1,DevNegi BollywoodDance Kedarnath 1
43,Namo Namo,AmitTrivedi,BollywoodDevotional,Kedarnath,1,AmitTrivedi BollywoodDevotional Kedarnath 1
44,Qaafirana,ArijitSinghNikhitaGandhi,BollywoodRomantic,Kedarnath,1,ArijitSinghNikhitaGandhi BollywoodRomantic Ked...
45,Tu Hi Re,ArmaanMalikShashaaTirupati,BollywoodDance,NaN,1,NaN
46,Chhote Chhote Peg,NavrajHansNehaKakkarYoYoHoneySingh,BollywoodDance,"Sonu,Ke,Titu,Ki,Sweety",1,NavrajHansNehaKakkarYoYoHoneySingh BollywoodDa...
47,Galti Se Mistake,AmitMishraArijitSingh,BollywoodDance,"Jagga,Jasoos",1,"AmitMishraArijitSingh BollywoodDance Jagga,Jas..."
48,Phir Mulaaqat,JubinNautiyal,BollywoodRomantic,"Cheat,India",1,"JubinNautiyal BollywoodRomantic Cheat,India 1"
49,Kala Chashma,AmarArshiBadshahNehaKakkar,BollywoodDance,"Baar,Baar,Dekho",1,AmarArshiBadshahNehaKakkar BollywoodDance Baar...

In [ ]:
import pickle
pickle.dump(new_df, open('musicrec.pkl', 'wb'))

In [ ]:
pickle.dump(similarity, open('similarities.pkl', 'wb'))